using '../../../../../../bicep/infra/citadel-access-contracts/main.bicep'

param apim = {
  subscriptionId: 'b881797f-b05b-4743-8516-17a967f31841'
  resourceGroupName: 'rg-citadel-workshop'
  name: 'apim-6dm44zbv4ms4s'
}

param keyVault = {
  subscriptionId: 'b881797f-b05b-4743-8516-17a967f31841'
  resourceGroupName: 'rg-citadel-workshop-spoke-1'
  name: 'kvcitadelworkshopspoke1b'
}

param useTargetAzureKeyVault = true

param useCase = {
  businessUnit: 'PF'
  useCaseName: 'ProductFinderAgentAccess'
  environment: 'DEV'
}

param apiNameMapping = {
  AGT: ['pf-agents-api']
}

param services = [
  {
    code: 'AGT'
    endpointSecretName: 'PF_AGENT_ENDPOINT'
    apiKeySecretName: 'PF_AGENT_KEY'
    policyXml: loadTextContent('ai-product-policy.xml')
  }
]

param productTerms = 'Product Finder specialist-agent access contract (generated by Notebook 4)'

param useTargetFoundry = true
param foundry = {
  subscriptionId: 'b881797f-b05b-4743-8516-17a967f31841'
  resourceGroupName: 'rg-citadel-workshop-spoke-1'
  accountName: 'aif-citadel-workshop-spoke-1-b881797f'
  projectName: 'citadel-agents-project'
}

param foundryConfig = {
  connectionNamePrefix: 'Product-Finder-DEV'
  connectionCategory: 'ApiManagement'
  deploymentInPath: 'false'
  isSharedToAll: false
  inferenceAPIVersion: '2025-03-01-preview'
  deploymentAPIVersion: ''
  staticModels: []
  listModelsEndpoint: ''
  getModelEndpoint: ''
  deploymentProvider: ''
  customHeaders: {}
  authConfig: {}
}
